spring.application.name=library-management-system
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/librarydb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

books.issue.max-allowed=3
books.issue.duration= 15
books.fine.per-day=2

